name: WalkieTalkiePlugin
version: '1.0-Alpha'
main: me.Luki.WalkieTalkiePlugin.WalkieTalkiePlugin
api-version: '1.21'
load: STARTUP
softdepend: [ voicechat, ItemsAdder, ProtocolLib ]
authors: [ Luki & StreamCraft ]
description: Walkie Talkie Plugin for StreamCraft 3, Simple Voice Chat extension

commands:

  walkietalkie:
    description: WalkieTalkiePlugin main command
    usage: /<command> <reload|info>
    aliases: [ wt ]

permissions:

  walkietalkie.reload:
    description: Allows reloading WalkieTalkiePlugin config
    default: op
  walkietalkie.info:
    description: Allows viewing WalkieTalkiePlugin info
    default: true
