name: WalkieTalkiePlugin
version: '${version}'
main: me.Luki.WalkieTalkiePlugin.WalkieTalkiePlugin
api-version: '1.21'
load: STARTUP
softdepend: [ voicechat, ItemsAdder, ProtocolLib ]
authors: [ Luki, StreamCraft ]
description: Walkie Talkie Plugin for StreamCraft 3, Simple Voice Chat extension

commands:
  walkietalkie:
    description: WalkieTalkiePlugin main command
    usage: /<command> <reload|info>
    aliases: [ wt ]

permissions:
  radio.use.*:
    description: Allows using any radio channel
    default: false
    children:
      radio.use.czerwoni: true
      radio.use.niebiescy: true
      radio.use.handlarze: true
      radio.use.piraci: true
      radio.use.tohandlarze: true

  radio.listen.*:
    description: Allows listening to any radio channel
    default: false
    children:
      radio.listen.czerwoni: true
      radio.listen.niebiescy: true
      radio.listen.handlarze: true
      radio.listen.piraci: true
      radio.listen.tohandlarze: true

  radio.craft.*:
    description: Allows crafting any radio channel
    default: false
    children:
      radio.craft.czerwoni: true
      radio.craft.niebiescy: true
      radio.craft.handlarze: true
      radio.craft.piraci: true
      radio.craft.tohandlarze: true
      radio.craft.randomchannel.piraci: true

  radio.use.czerwoni:
    description: Allows using red team radio
    default: false
  radio.listen.czerwoni:
    description: Allows listening to red team radio
    default: false
  radio.craft.czerwoni:
    description: Allows crafting red team radio
    default: false

  radio.use.niebiescy:
    description: Allows using blue team radio
    default: false
  radio.listen.niebiescy:
    description: Allows listening to blue team radio
    default: false
  radio.craft.niebiescy:
    description: Allows crafting blue team radio
    default: false

  radio.use.handlarze:
    description: Allows using merchants radio
    default: false
  radio.listen.handlarze:
    description: Allows listening to merchants radio
    default: false
  radio.craft.handlarze:
    description: Allows crafting merchants radio
    default: false

  radio.use.piraci:
    description: Allows using pirates radio
    default: false
  radio.listen.piraci:
    description: Allows listening to pirates radio
    default: false
  radio.craft.piraci:
    description: Allows crafting pirates radio
    default: false

  radio.use.tohandlarze:
    description: Allows using "to merchants" radio
    default: false
  radio.listen.tohandlarze:
    description: Allows listening to "to merchants" radio
    default: false
  radio.craft.tohandlarze:
    description: Allows crafting "to merchants" radio
    default: false

  radio.randomChannel.piraci:
    description: Allows using pirate random channel radio (use/listen)
    default: false
  radio.craft.randomchannel.piraci:
    description: Allows crafting pirate random channel radio
    default: false

  walkietalkie.reload:
    description: Allows reloading WalkieTalkiePlugin config
    default: op
  walkietalkie.info:
    description: Allows viewing WalkieTalkiePlugin info
    default: true
